POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
"email":"abdela@gmail.com",
"password":"12345678"
}

###
### GET Request
GET http://localhost:3000/api/users/6784c8ac9ce03e2cb9b013ea
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODRjOGFjOWNlMDNlMmNiOWIwMTNlYSIsImlhdCI6MTczNjc4OTI5OCwiZXhwIjoxNzM2NzkyODk4fQ.H5zsbl46Y_uKxcbIKuaE3ZBuJRsQZxY9vx-G39OzDL4
Content-Type: application/json


